sudo: false
language: java
script: mvn -Dmaven.test.skip=true clean source:jar deploy --settings mvn_settings.xml --fail-at-end
jdk:
  - oraclejdk8
# whitelist
branches:
  only:
    - master
notifications:
  email: false
before_install:
  - export TZ=Asia/Shanghai
